# Generated by Django 3.0.8 on 2020-07-14 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmaster', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='person',
        ),
    ]
