# Generated by Django 3.0.8 on 2020-07-17 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmaster', '0006_auto_20200715_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='task',
            name='time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
